Добавить функционал согласно ТЗ 11.2
galievranis/java-filmorate pull request #4
Opened 2023-03-03 11:17 UTC by galievranis

2023-03-04 10:22 UTC, zgreen3 requested changes
Привет. 
Проверил проект, в целом он соответствует ТЗ, отлично 
(особенно мне понравилось как реализована вся, связанная с Java-кодом часть работы, все ключевые и сложные моменты выполнены хорошо и в соответствии с ТЗ - супер)!
 
После возможной правки кода на основе комментариев и (или) принятия их к сведению ("Надо исправить" - в этот раз таких комментариев +/-1 - и "Можно лучше"), присылай работу на завершение проверки.
Спасибо.

2023-03-04 10:22 UTC, zgreen3 commented on pom.xml
> +		<dependency>
Отлично:
Нужные зависимости по работе с БД добавлены в полном соответствии с ТЗ, отлично!

+Можно лучше (комментарий к файлу README.md):
В большинстве профессиональных проектов на GitHub на этапе получения первой полнофункциональной версии проекта (для проекта Filmorate - это как раз задание данного спринта) принято оформлять README файл в разметке markdown (https://www.markdownguide.org/cheat-sheet/), описывающий кратко основной функционал проекта, и/или технические детали его работы для других разработчиков, которые могут использовать его код. В данном учебном проекте полезно добавить в этот файл схему БД (набор таблиц с их полями и типами данных и связей между ними), которая используется слоем хранилища данных, это можно сделать, например, в виде картинки (`![alt text](image.jpg)`), также добавив её в репозиторий, в директорию ресурсов, для возможности ссылаться на неё.

2023-03-04 10:22 UTC, zgreen3 commented on src/main/resources/application.properties
> +spring.sql.init.mode=always
Отлично:
Вижу, что добавлены все нужные настройки для конфигурования базы данных H2 для рабочего режима, в полном соответствии с ТЗ, отлично!

2023-03-04 10:22 UTC, zgreen3 commented on src/main/resources/schema.sql
> +    film_id BIGINT PRIMARY KEY AUTO_INCREMENT,
Можно лучше:
Технически данный подход с AUTO_INCREMENT корректен, при этом в последних версиях H2 появился более новый подход (полнее соответствующий стандартам SQL) с применением другого ключевого поля IDENTITY, см. некоторые детали на англ. яз. тут, http://h2database.com/html/features.html?highlight=generated&search=GENERATED#compatibility, https://stackoverflow.com/a/72405103, https://stackoverflow.com/a/53605454.

2023-03-04 10:22 UTC, zgreen3 commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS movies_ratings (
Можно лучше:
Поскольку между таблицей фильмов и таблицей рейтингов имеется отношение многие к одному (т.к. много фильмов может относиться к одному рейтингу, но много рейтингов mpaa (исходя из имеющейся логики предметной области для этого рейтинга и предыдущих ТЗ)  не могут относится к одному фильму, другими словами, только один рейтинг может относиться к одному фильму), постольку можно упростить схему БД в этой части, исключив данную таблицу и внеся rating_id непосредственно в таблицу фильмов.

2023-03-04 10:22 UTC, zgreen3 commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS movies (
Отлично:
Вижу, что корректно добавлены скрипты `schema.sql`, `data.sql`, в полном соответствии с ТЗ, отлично!

2023-03-04 10:22 UTC, zgreen3 commented on src/main/resources/schema.sql
> +
Можно лучше:
Вероятно, вы ещё не проходили углублённо на курсе, или немного затрагивали тему индексов в БД. В любом случае, полезно иметь ввиду, что если примерно известно или можно уверенно предположить, что пользователи приложения (в т.ч. не только конечные пользователи, но и тезнические - пользователи API нашего бэкэнд-приложения) будут часто осуществлять поиск по каким-то полям БД, то имеет смысл добавить индексы на такие поля.
Например, в данном случае это могли бы быть такие индексы:
```
create unique index if not exists USER_EMAIL_UINDEX on USERS (email);
create unique index if not exists USER_LOGIN_UINDEX on USERS (login);
```

2023-03-04 10:22 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        final String sqlQuery = "SELECT * FROM movies";
Можно лучше / +/-Надо (лучше)) исправить (если есть время):
Данная реализация технически корректна, при этом из-за вызова таблицы с жанрами в меппере далее к БД будет осуществлено столько же запросов к таблице, связывающий фильмы и жанры, сколько у нас хранится фильмов в таблице фильмов.
Оптимальнее было бы здесь сделать запрос к БД с соединением (join) таблицы фильмов и таблицы жанров через третью таблицу их связи (фильмы-жанры). Если такой запрос будет сложно реализовать, то на следующей итерации проверки я опишу его подробнее. Для хорошего прогресса в работе с sql важно сначала попробовать его сделать самостоятельно.

2023-03-04 10:36 UTC, galievranis commented on pom.xml
> +		<dependency>
Да, точно. Я ее забыл в самом проекте добавить, но в гитхабе я ее вставил)

2023-03-04 10:48 UTC, galievranis commented on src/main/resources/schema.sql
> +    film_id BIGINT PRIMARY KEY AUTO_INCREMENT,
Исправил

2023-03-04 11:15 UTC, galievranis commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS movies_ratings (
Исправил. Также переделал схему БД

2023-03-04 11:17 UTC, galievranis commented on src/main/resources/schema.sql
> +
Про индексы пока не проходили, поэтому этот пункт пропущу пока, но принял к сведению, спасибо!

2023-03-05 00:28 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        final String sqlQuery = "SELECT * FROM movies";
Отлично:
Когда я писал комментарий выше на предыдущей итерации проверки, то недосмотрел, что запрос здесь нужно чтобы возвращал по одной записи на фильм, иначе меппер далее в коде не сработает нужным образом.

Поэтому здесь пришлось бы не просто join-ить 3 таблицы для получения всех жанров всех фильмов, но и использовать потом группировку по ИД фильма и агрегирующую функцию H2 вроде `SELECT film_id, GROUP_CONCAT(DISTINCT genre_id SEPARATOR ', ') genre_id FROM movies AS m JOIN movies_genres AS mg ON  m.film_id = mg.film_id JOIN genres AS g ON mg.genre_id = g.genre_id GROUP BY film_id `, но это всё сильно бы усложнило как сам мэппер, так и отладку самого запроса к БД (sql-код выше я, честно говоря, не успел проверить на рабочей БД, так что он не отлажен), поэтому выглядит сейчас нецелесообразным.

Извини, что сразу не увидел вышеописанные проблемы с предложенным мной подходом здесь =(). В любом случае, хорошо, что ты попробовал сам поразбираться в этом вопросе.

Сейчас предлагаю оставить всё как есть и двигаться дальше (если у меня появятся идеи, как оптимизировать вышеуказанный процесс, то я напишу или в нашей переписке в Пачке, или в рамках следующего код-ревью).

2023-03-05 00:31 UTC, zgreen3 approved these changes
Привет, вижу, что ты учёл все важные комментарии, отлично! 
Принимаю проект в текущем виде, встретимся на проверке следующих проектов.

2023-03-05 04:13 UTC, merged